/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'rjv9645' at '2/21/17 6:12 PM' with Gradle 2.14.1
 *
 * @author rjv9645, @date 2/21/17 6:12 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
