CREATE TABLE LOCATIONS (
ID INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY 
	(START WITH 1, INCREMENT BY 1),
ADDRESS VARCHAR(100),
ADDREXT VARCHAR(50),
LONGITUDE FLOAT(16),
LATITUDE FLOAT(16),
CITY VARCHAR(50),
STATE VARCHAR(2),
ZIP VARCHAR(6)
)